<?php include('config.php'); 
$var="one";
$query = "INSERT INTO `list`(`string`,`1`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$var="sumit";
$query = "INSERT INTO `list`(`string`,`1`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$query = "UPDATE `list` SET `1`=2 WHERE `string`='sumit';";
mysqli_query($con,$query);
$query = "UPDATE `list` SET `1`=3 WHERE `string`='sumit';";
mysqli_query($con,$query);
$query = "UPDATE `list` SET `1`=4 WHERE `string`='sumit';";
mysqli_query($con,$query);
$var="two";
$query = "INSERT INTO `list`(`string`,`2`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$query = "UPDATE `list` SET `2`=1 WHERE `string`='sumit';";
mysqli_query($con,$query);
$var="four";
$query = "INSERT INTO `list`(`string`,`2`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$query = "UPDATE `list` SET `2`=2 WHERE `string`='four';";
mysqli_query($con,$query);
$query = "UPDATE `list` SET `2`=3 WHERE `string`='four';";
mysqli_query($con,$query);
$var="Tennis";
$query = "INSERT INTO `list`(`string`,`2`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$var="is";
$query = "INSERT INTO `list`(`string`,`2`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$var="a";
$query = "INSERT INTO `list`(`string`,`2`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$var="racket";
$query = "INSERT INTO `list`(`string`,`2`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$var="sport";
$query = "INSERT INTO `list`(`string`,`2`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$var="that";
$query = "INSERT INTO `list`(`string`,`2`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$var="can";
$query = "INSERT INTO `list`(`string`,`2`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$var="be";
$query = "INSERT INTO `list`(`string`,`2`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$var="played";
$query = "INSERT INTO `list`(`string`,`2`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$var="individually";
$query = "INSERT INTO `list`(`string`,`2`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$var="against";
$query = "INSERT INTO `list`(`string`,`2`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$query = "UPDATE `list` SET `2`=2 WHERE `string`='a';";
mysqli_query($con,$query);
$var="single";
$query = "INSERT INTO `list`(`string`,`2`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$var="opponent";
$query = "INSERT INTO `list`(`string`,`2`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$var="singles";
$query = "INSERT INTO `list`(`string`,`2`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$var="or";
$query = "INSERT INTO `list`(`string`,`2`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$var="between";
$query = "INSERT INTO `list`(`string`,`2`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$query = "UPDATE `list` SET `2`=2 WHERE `string`='two';";
mysqli_query($con,$query);
$var="teams";
$query = "INSERT INTO `list`(`string`,`2`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$var="of";
$query = "INSERT INTO `list`(`string`,`2`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$query = "UPDATE `list` SET `2`=3 WHERE `string`='two';";
mysqli_query($con,$query);
$var="players";
$query = "INSERT INTO `list`(`string`,`2`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$var="each";
$query = "INSERT INTO `list`(`string`,`2`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$var="doubles";
$query = "INSERT INTO `list`(`string`,`2`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$var="Each";
$query = "INSERT INTO `list`(`string`,`2`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$var="player";
$query = "INSERT INTO `list`(`string`,`2`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$var="uses";
$query = "INSERT INTO `list`(`string`,`2`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$query = "UPDATE `list` SET `2`=3 WHERE `string`='a';";
mysqli_query($con,$query);
$var="tennis";
$query = "INSERT INTO `list`(`string`,`2`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$query = "UPDATE `list` SET `2`=2 WHERE `string`='racket';";
mysqli_query($con,$query);
$var="three";
$query = "INSERT INTO `list`(`string`,`3`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$query = "UPDATE `list` SET `3`=1 WHERE `string`='sumit';";
mysqli_query($con,$query);
$query = "UPDATE `list` SET `3`=2 WHERE `string`='sumit';";
mysqli_query($con,$query);
$query = "UPDATE `list` SET `3`=2 WHERE `string`='three';";
mysqli_query($con,$query);
$var="Lets";
$query = "INSERT INTO `list`(`string`,`3`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$query = "UPDATE `list` SET `3`=1 WHERE `string`='be';";
mysqli_query($con,$query);
$var="clear";
$query = "INSERT INTO `list`(`string`,`3`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$var="about";
$query = "INSERT INTO `list`(`string`,`3`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$query = "UPDATE `list` SET `3`=1 WHERE `string`='one';";
mysqli_query($con,$query);
$var="thing";
$query = "INSERT INTO `list`(`string`,`3`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$var="While";
$query = "INSERT INTO `list`(`string`,`3`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$var="Roger";
$query = "INSERT INTO `list`(`string`,`3`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$var="Federer";
$query = "INSERT INTO `list`(`string`,`3`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$var="would";
$query = "INSERT INTO `list`(`string`,`3`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$var="welcome";
$query = "INSERT INTO `list`(`string`,`3`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$query = "UPDATE `list` SET `3`=1 WHERE `string`='a';";
mysqli_query($con,$query);
$var="oldest";
$query = "INSERT INTO `list`(`string`,`4`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$var="rock";
$query = "INSERT INTO `list`(`string`,`4`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$var="formation";
$query = "INSERT INTO `list`(`string`,`4`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$var="some";
$query = "INSERT INTO `list`(`string`,`4`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$var="over";
$query = "INSERT INTO `list`(`string`,`4`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$query = "UPDATE `list` SET `4`=1 WHERE `string`='one';";
mysqli_query($con,$query);
$var="billion";
$query = "INSERT INTO `list`(`string`,`4`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$var="years";
$query = "INSERT INTO `list`(`string`,`4`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$var="old";
$query = "INSERT INTO `list`(`string`,`4`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$var="Constituted";
$query = "INSERT INTO `list`(`string`,`4`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$var="in";
$query = "INSERT INTO `list`(`string`,`4`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$var="such";
$query = "INSERT INTO `list`(`string`,`4`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$var="fashio";
$query = "INSERT INTO `list`(`string`,`4`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$var="India";
$query = "INSERT INTO `list`(`string`,`4`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$var="lies";
$query = "INSERT INTO `list`(`string`,`4`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$var="to";
$query = "INSERT INTO `list`(`string`,`4`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$var="the";
$query = "INSERT INTO `list`(`string`,`4`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$var="north";
$query = "INSERT INTO `list`(`string`,`4`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$query = "UPDATE `list` SET `4`=1 WHERE `string`='of';";
mysqli_query($con,$query);
$query = "UPDATE `list` SET `4`=2 WHERE `string`='the';";
mysqli_query($con,$query);
$var="equator";
$query = "INSERT INTO `list`(`string`,`4`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$query = "UPDATE `list` SET `4`=1 WHERE `string`='between';";
mysqli_query($con,$query);
$var="east";
$query = "INSERT INTO `list`(`string`,`4`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$var="longitude127";
$query = "INSERT INTO `list`(`string`,`4`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$var="The";
$query = "INSERT INTO `list`(`string`,`5`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$var="Americas";
$query = "INSERT INTO `list`(`string`,`5`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$var="also";
$query = "INSERT INTO `list`(`string`,`5`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$var="collectively";
$query = "INSERT INTO `list`(`string`,`5`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$var="called";
$query = "INSERT INTO `list`(`string`,`5`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$var="America";
$query = "INSERT INTO `list`(`string`,`5`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$var="encompass";
$query = "INSERT INTO `list`(`string`,`5`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$query = "UPDATE `list` SET `5`=1 WHERE `string`='the';";
mysqli_query($con,$query);
$var="totality";
$query = "INSERT INTO `list`(`string`,`5`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$query = "UPDATE `list` SET `5`=1 WHERE `string`='of';";
mysqli_query($con,$query);
$query = "UPDATE `list` SET `5`=2 WHERE `string`='the';";
mysqli_query($con,$query);
$var="continents";
$query = "INSERT INTO `list`(`string`,`5`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
$query = "UPDATE `list` SET `5`=2 WHERE `string`='of';";
mysqli_query($con,$query);
$var="North";
$query = "INSERT INTO `list`(`string`,`5`)VALUES ('".$var."',1);";
mysqli_query($con,$query);
header("Location:display.php");?>